'use client';
import { useEffect, useState } from 'react';
import { createClient } from '@/lib/supabase/client';
import type { CommunityPost, CommunityReply, Profile } from '@/lib/community-types';
const reasons = ['SPAM', 'HARASSMENT', 'HATE', 'SEXUAL CONTENT', 'VIOLENCE', 'DANGEROUS ADVICE', 'OTHER'];

export default function CommunityPostDetail({ id }: { id: string }) {
  const [post, setPost] = useState<CommunityPost | null>(null); const [author, setAuthor] = useState<Profile | null>(null); const [replies, setReplies] = useState<CommunityReply[]>([]); const [people, setPeople] = useState<Profile[]>([]); const [userId, setUserId] = useState(''); const [prayed, setPrayed] = useState(false); const [prayerCount, setPrayerCount] = useState(0); const [reply, setReply] = useState(''); const [reporting, setReporting] = useState<string | null>(null); const [reason, setReason] = useState(reasons[0]); const [details, setDetails] = useState(''); const [error, setError] = useState(''); const client = createClient();
  async function load() { if (!client) return; const auth = await client.auth.getUser(); if (!auth.data.user) return; setUserId(auth.data.user.id); const result = await client.from('community_posts').select('*').eq('id', id).eq('is_deleted', false).maybeSingle(); if (!result.data) return; const item = result.data as CommunityPost; setPost(item); const [authorResult, repliesResult, ownPrayer, prayers] = await Promise.all([client.from('profiles').select('*').eq('id', item.user_id).maybeSingle(), client.from('community_replies').select('*').eq('post_id', id).eq('is_deleted', false).order('created_at'), client.from('community_prayers').select('id').eq('post_id', id).eq('user_id', auth.data.user.id).maybeSingle(), client.from('community_prayers').select('id', { count: 'exact', head: true }).eq('post_id', id)]); setAuthor(authorResult.data as Profile | null); const nextReplies = (repliesResult.data || []) as CommunityReply[]; setReplies(nextReplies); setPrayed(!!ownPrayer.data); setPrayerCount(prayers.count || 0); if (nextReplies.length) { const profileResult = await client.from('profiles').select('*').in('id', nextReplies.map(item => item.user_id)); setPeople((profileResult.data || []) as Profile[]); } }
  useEffect(() => { void load(); }, [id]);
  async function togglePrayer() { if (!client || !userId) return; const result = prayed ? await client.from('community_prayers').delete().eq('post_id', id).eq('user_id', userId) : await client.from('community_prayers').insert({ post_id: id, user_id: userId }); if (result.error) setError(result.error.message); else await load(); }
  async function submitReply(event: React.FormEvent) { event.preventDefault(); if (!client || !reply.trim()) return; const result = await client.from('community_replies').insert({ post_id: id, user_id: userId, body: reply.trim() }); if (result.error) setError(result.error.message); else { setReply(''); await load(); } }
  async function submitReport(event: React.FormEvent, postId: string | null, replyId: string | null) { event.preventDefault(); if (!client) return; const result = await client.from('community_reports').insert({ post_id: postId, reply_id: replyId, reporter_user_id: userId, reason, details: details.trim() || null }); if (result.error) setError(result.error.message); else { setReporting(null); setDetails(''); setError('REPORT RECEIVED'); } }
  if (!post) return <p className="py-20 text-center mono text-[10px] text-[#85847d]">POST NOT FOUND.</p>;
  const peopleMap = new Map(people.map(person => [person.id, person]));
  return <article><a href="/community" className="mono text-[10px] text-[#85847d]">← BACK TO GARRISON</a><div className="mt-14 border-b border-white/[.14] pb-10"><p className="mono text-[10px] text-[#a08b5c]">{post.type} / {post.id.slice(0, 4)}</p><h1 className="display mt-6 text-[clamp(3rem,7vw,6rem)] leading-[.84]">{post.title}</h1><p className="mt-6 text-sm text-[#85847d]">@{author?.username || 'UNKNOWN'} · {new Date(post.created_at).toLocaleDateString()}</p></div><p className="serif max-w-3xl whitespace-pre-wrap pt-12 text-[20px] leading-[1.8] text-[#dedbd0]">{post.body}</p><div className="mt-12 flex flex-wrap items-center gap-5"><button onClick={togglePrayer} className={`mono border px-5 py-3 text-[10px] ${prayed ? 'border-[#a08b5c] text-[#a08b5c]' : 'border-[#343532]'}`}>I PRAYED †</button><span className="mono text-[10px] text-[#85847d]">{prayerCount} PEOPLE PRAYED</span><a href="#replies" className="mono border border-[#343532] px-5 py-3 text-[10px]">REPLY</a><button onClick={() => setReporting(reporting === 'post' ? null : 'post')} className="mono px-5 py-3 text-[10px] text-[#85847d]">REPORT</button></div>{reporting === 'post' && <ReportForm reason={reason} setReason={setReason} details={details} setDetails={setDetails} onSubmit={event => submitReport(event, id, null)}/>} {error && <p className="mt-6 text-sm text-[#a08b5c]">{error}</p>}<section id="replies" className="mt-20 border-t border-white/[.14] pt-10"><p className="mono mb-7 text-[10px] text-[#85847d]">REPLIES / {String(replies.length).padStart(2, '0')}</p>{replies.map(item => <div key={item.id} className="border-b border-white/[.14] py-5"><div className="flex items-center justify-between"><p className="mono text-[10px] text-[#85847d]">@{peopleMap.get(item.user_id)?.username || 'UNKNOWN'}</p><button onClick={() => setReporting(reporting === item.id ? null : item.id)} className="mono text-[9px] text-[#85847d]">REPORT</button></div><p className="serif mt-3 text-[17px] leading-relaxed text-[#aaa9a1]">{item.body}</p>{reporting === item.id && <ReportForm reason={reason} setReason={setReason} details={details} setDetails={setDetails} onSubmit={event => submitReport(event, null, item.id)}/>}</div>)}<form onSubmit={submitReply} className="mt-8"><textarea required maxLength={3000} value={reply} onChange={event => setReply(event.target.value)} placeholder="Write a reply" className="w-full border border-[#343532] bg-[#050505] p-4 text-base text-[#dedbd0]"/><button className="mono mt-4 border border-[#aaa9a1] px-5 py-3 text-[10px]">POST REPLY</button></form></section></article>;
}
function ReportForm({ reason, setReason, details, setDetails, onSubmit }: { reason: string; setReason: (value: string) => void; details: string; setDetails: (value: string) => void; onSubmit: (event: React.FormEvent) => void }) { return <form onSubmit={onSubmit} className="mt-5 border border-[#343532] p-5"><label className="mono block text-[10px]">REASON<select value={reason} onChange={event => setReason(event.target.value)} className="mt-2 h-11 w-full border border-[#343532] bg-[#050505] px-3 font-sans text-base tracking-normal text-[#dedbd0]">{reasons.map(item => <option key={item}>{item}</option>)}</select></label><textarea value={details} onChange={event => setDetails(event.target.value)} placeholder="Optional details" className="mt-4 w-full border border-[#343532] bg-[#050505] p-3 text-base text-[#dedbd0]"/><button className="mono mt-4 border border-[#aaa9a1] px-4 py-3 text-[10px]">SEND REPORT</button></form>; }
