import type { Metadata } from 'next';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import FieldGuideArticle from '@/components/FieldGuideArticle';
import { fieldGuides, getFieldGuide } from '@/data/fieldGuides';
import { notFound } from 'next/navigation';
import JsonLd from '@/components/JsonLd';

export function generateStaticParams() { return fieldGuides.map(guide => ({ slug: guide.slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const guide = getFieldGuide(slug); if (!guide) return {}; const titles: Record<string, string> = { 'spiritual-warfare': 'Spiritual Warfare: A Biblical Guide | RebukeEvil', 'armor-of-god': 'The Armor of God Explained | RebukeEvil', 'resist-the-devil': 'How to Resist the Devil Biblically | RebukeEvil', 'what-does-rebuke-mean': 'What Does Rebuke Mean in the Bible? | RebukeEvil', 'overcome-evil-with-good': 'Overcome Evil With Good: Romans 12:21 | RebukeEvil', 'the-name-of-jesus': 'The Name of Jesus: Biblical Meaning & Authority | RebukeEvil' }; const descriptions: Record<string, string> = { 'spiritual-warfare': 'A biblical guide to spiritual warfare, the Bible, Ephesians 6, the armor of God, resisting temptation, and standing firm in Christ.', 'armor-of-god': 'Understand Ephesians 6 and the armor of God through Scripture, prayer, truth, faith, and obedience.', 'resist-the-devil': 'Learn how to submit to God, resist the devil biblically, resist temptation, and stand firm in faith.', 'what-does-rebuke-mean': 'What rebuke means in the Bible, how Scripture uses the word, and how correction remains grounded in truth and humility.', 'overcome-evil-with-good': 'A biblical guide to Romans 12:21, forgiveness, wise boundaries, and overcoming evil with good.', 'the-name-of-jesus': 'Understand the biblical authority of Jesus Christ and what it means to pray and stand in His name.' }; return { title: titles[slug], description: descriptions[slug], alternates: { canonical: `https://rebukeevil.com/field-guides/${slug}` } }; }
export default async function FieldGuidePage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const guide = getFieldGuide(slug); if (!guide) notFound(); const index = fieldGuides.findIndex(item => item.slug === slug); return <><Header/><JsonLd data={{ '@context': 'https://schema.org', '@type': 'Article', headline: guide.title, description: guide.description, url: `https://rebukeevil.com/field-guides/${slug}`, breadcrumb: { '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Field Guides', item: 'https://rebukeevil.com/field-guides' }, { '@type': 'ListItem', position: 2, name: guide.title, item: `https://rebukeevil.com/field-guides/${slug}` }] } }}/><main><FieldGuideArticle guide={guide} previous={fieldGuides[index - 1]} next={fieldGuides[index + 1]}/></main><Footer/></>; }
