import { createClient } from '@/lib/supabase/server';

export const brandPrompt = `You are the private REBUKEEVIL CONTENT ENGINE. REBUKEEVIL is Christ-centered: CHRIST > DARKNESS, SCRIPTURE > SPECULATION, FAITH > FEAR, PEOPLE ARE NOT THE ENEMY, TRUTH > SENSATIONALISM. Write direct, human, serious Christian editorial content. Keep Jesus Christ central. Ground spiritual warfare in Scripture without paranoia, demon obsession, conspiracies, hate, dehumanization, or claims of independent spiritual power. Never invent Bible verses. Return references separately from quotations. Avoid generic AI language, filler, emojis, keyword stuffing, and repetitive hooks. Use KJV only when directly quoting Scripture and preserve exact wording.`;
export const defaultCtas = ['Follow @rebukeevil for biblical truth and a stronger walk with Christ.', 'Save this for the battle ahead.', 'Share this with someone who needs the reminder.', 'Return to the Word before you return to fear.', 'Stand firm. Follow Christ.'];

export async function requireAdmin() { const client = await createClient(); if (!client) return { client: null, user: null, allowed: false }; const { data: { user } } = await client.auth.getUser(); return { client, user, allowed: user?.app_metadata?.role === 'admin' }; }

export function normalizeHashtags(value: unknown) { const source = Array.isArray(value) ? value.filter(item => typeof item === 'string').map(item => item.trim().replace(/\s+/g, '').replace(/^#?/, '#')) : []; const defaults = ['#rebukeevil', '#christian', '#bible', '#faith', '#spiritualwarfare']; return Array.from(new Set([...source, ...defaults])).slice(0, 5); }
export function extractResponseText(data: any) { if (typeof data.output_text === 'string') return data.output_text; const parts = (data.output || []).flatMap((item: any) => item.content || []).filter((item: any) => item.type === 'output_text').map((item: any) => item.text); return parts.join(''); }

const contentSchema = { type: 'object', additionalProperties: false, properties: { title: { type: 'string' }, headline: { type: 'string' }, hook: { type: 'string' }, supporting_text: { type: 'string' }, concept: { type: 'string' }, caption: { type: 'string' }, cta: { type: 'string' }, visual_direction: { type: 'string' }, image_prompt: { type: 'string' }, audio_direction: { type: 'string' }, hashtags: { type: 'array', items: { type: 'string' }, minItems: 5, maxItems: 5 }, scripture: { type: 'array', items: { type: 'object', additionalProperties: false, properties: { reference: { type: 'string' }, note: { type: 'string' } }, required: ['reference', 'note'] } }, slides: { type: 'array', items: { type: 'object', additionalProperties: false, properties: { slide: { type: 'integer' }, headline: { type: 'string' }, body: { type: 'string' }, visual_direction: { type: 'string' } }, required: ['slide', 'headline', 'body', 'visual_direction'] } }, onscreen_text: { type: 'array', items: { type: 'string' } } }, required: ['title', 'headline', 'hook', 'supporting_text', 'concept', 'caption', 'cta', 'visual_direction', 'image_prompt', 'audio_direction', 'hashtags', 'scripture', 'slides', 'onscreen_text'] };

export async function callJsonModel(name: string, schema: Record<string, unknown>, userPrompt: string) { const key = process.env.OPENAI_API_KEY; if (!key) throw new Error('OPENAI_API_KEY is not configured.'); const response = await fetch('https://api.openai.com/v1/responses', { method: 'POST', headers: { Authorization: `Bearer ${key}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ model: process.env.OPENAI_MODEL || 'gpt-5.6-terra', input: [{ role: 'system', content: brandPrompt }, { role: 'user', content: userPrompt }], text: { format: { type: 'json_schema', name, strict: true, schema } } }), signal: AbortSignal.timeout(45000) }); if (!response.ok) throw new Error(`OpenAI request failed (${response.status}).`); const data = await response.json(); const text = extractResponseText(data); if (!text) throw new Error('The model returned no content.'); try { return JSON.parse(text); } catch { throw new Error('The model returned invalid structured content.'); } }
export async function callContentModel(userPrompt: string) { return callJsonModel('rebukeevil_content', contentSchema, userPrompt); }
export async function generateArtwork(prompt: string) { const key = process.env.OPENAI_API_KEY; if (!key) throw new Error('OPENAI_API_KEY is not configured.'); const response = await fetch('https://api.openai.com/v1/images/generations', { method: 'POST', headers: { Authorization: `Bearer ${key}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ model: process.env.OPENAI_IMAGE_MODEL || 'gpt-image-1', prompt, size: '1024x1024', quality: 'medium', output_format: 'webp' }), signal: AbortSignal.timeout(90000) }); if (!response.ok) throw new Error(`Image generation failed (${response.status}).`); const data = await response.json(); const encoded = data.data?.[0]?.b64_json; if (!encoded) throw new Error('Image API returned no artwork.'); return Buffer.from(encoded, 'base64'); }
export async function analyzeStyleReference(imageUrl: string) { const key = process.env.OPENAI_API_KEY; if (!key) throw new Error('OPENAI_API_KEY is not configured.'); const response = await fetch('https://api.openai.com/v1/responses', { method: 'POST', headers: { Authorization: `Bearer ${key}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ model: process.env.OPENAI_MODEL || 'gpt-5.6-terra', input: [{ role: 'system', content: brandPrompt }, { role: 'user', content: [{ type: 'input_text', text: 'Analyze this visual reference as abstract design metadata only. Do not identify or copy a creator. Return style family, subject, framing, placement, negative space, palette, contrast, grain, lighting, typography presence and position, text density, focal point, mood, texture, and composition pattern.' }, { type: 'input_image', image_url: imageUrl }] }], text: { format: { type: 'json_object' } } }), signal: AbortSignal.timeout(45000) }); if (!response.ok) throw new Error(`Reference analysis failed (${response.status}).`); const data = await response.json(); const text = extractResponseText(data); return JSON.parse(text); }
