import { NextResponse } from 'next/server';
import { callContentModel, generateArtwork, normalizeHashtags, requireAdmin } from '@/lib/content-engine';
import { contentAngles, contentCategories } from '@/data/contentCategories';
export const dynamic = 'force-dynamic';
const formatWeights = [['3-Slide Carousel', 35], ['Single Post', 25], ['5-Slide Carousel', 20], ['Reel', 10], ['Scripture Post', 5], ['Threads Post', 5]] as const;
const categoryWeights = [['JESUS CHRIST', 23], ['SCRIPTURE', 18], ['SPIRITUAL WARFARE', 17], ['PRAYER', 12], ['FAITH', 12], ['SIN & TEMPTATION', 10], ['DISCIPLINE', 8]] as const;
const visualStyles = ['MODERN WARFARE', 'DEMONIC PRESENCE', 'CHRIST VICTORIOUS', 'CRUSADER / GARRISON', 'SCRIPTURE EDITORIAL', 'PRAYER / SOLITUDE', 'MODERN CULTURE', 'SIN SERIES', 'LIGHT VS DARKNESS', 'SPIRITUAL WARNING', 'JESUS / GOSPEL'];
const templates = ['HOOK + BODY', 'SCRIPTURE + REFLECTION', 'MYTH VS TRUTH', 'QUESTION + CONVICTION', 'THREE-BEAT PROGRESSION'];
function weighted<T>(items: readonly (readonly [T, number])[]) { const total = items.reduce((sum, item) => sum + item[1], 0); let point = Math.random() * total; for (const item of items) { point -= item[1]; if (point <= 0) return item[0]; } return items[items.length - 1][0]; }
function similarity(a: string, b: string) { const left = a.toLowerCase().split(/\W+/).filter(Boolean); const right = new Set(b.toLowerCase().split(/\W+/).filter(Boolean)); return left.length ? left.filter(word => right.has(word)).length / left.length : 0; }
function xml(value: string) { return String(value || '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&apos;'); }
function finalSlide(source: Buffer, headline: string, body: string, index: number, total: number) { const image = source.toString('base64'); return `<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1080" viewBox="0 0 1080 1080"><image width="1080" height="1080" preserveAspectRatio="xMidYMid slice" href="data:image/webp;base64,${image}"/><rect width="1080" height="1080" fill="#0e0e0c" opacity=".34"/><text x="72" y="82" fill="#e4d8c1" font-family="Georgia,serif" font-size="24" letter-spacing="6">REBUKEEVIL</text><text x="1008" y="82" text-anchor="end" fill="#a98c50" font-family="monospace" font-size="20" letter-spacing="3">${String(index).padStart(2, '0')} / ${String(total).padStart(2, '0')}</text><text x="72" y="710" fill="#f0e8d8" font-family="Georgia,serif" font-size="64" font-weight="bold">${xml(headline).slice(0, 52)}</text><text x="72" y="790" fill="#cfc0a2" font-family="Georgia,serif" font-size="30">${xml(body).slice(0, 90)}</text><rect x="72" y="930" width="936" height="2" fill="#a98c50" opacity=".8"/><text x="72" y="978" fill="#cfc0a2" font-family="monospace" font-size="18" letter-spacing="5">STAND FIRM. REBUKE EVIL. FOLLOW CHRIST.</text></svg>`; }

export async function POST() {
  const auth = await requireAdmin(); if (!auth.allowed || !auth.client || !auth.user) return NextResponse.json({ error: 'Unauthorized.' }, { status: 403 });
  const uploaded: string[] = [];
  try {
    const recent = await auth.client.from('content_drafts').select('title,hook,category,format,visual_direction,scripture').order('created_at', { ascending: false }).limit(30); const recentItems = recent.data || [];
    const recentCategories = new Set(recentItems.slice(0, 3).map(item => item.category)); const weightedNames = categoryWeights.filter(([name]) => !recentCategories.has(name)); const chosenName = weighted(weightedNames.length ? weightedNames : categoryWeights); const category = contentCategories.find(item => item.name === chosenName) || contentCategories[0]; const format = weighted(formatWeights); const angle = contentAngles[Math.floor(Math.random() * contentAngles.length)]; const visualPool = visualStyles.filter(style => !recentItems.slice(0, 5).some(item => (item.visual_direction || '').toUpperCase().includes(style))); const visualStyle = (visualPool.length ? visualPool : visualStyles)[Math.floor(Math.random() * (visualPool.length || visualStyles.length))]; const template = templates[Math.floor(Math.random() * templates.length)];
    let result: any; let score = 1;
    for (let attempt = 0; attempt < 3; attempt += 1) { const subcategory = category.subcategories[Math.floor(Math.random() * category.subcategories.length)]; result = await callContentModel(`AUTOPILOT STRATEGY: format=${format}; category=${category.name}; subcategory=${subcategory}; angle=${angle}; visual style=${visualStyle}; template=${template}. Choose final audience, intensity, Jesus focus, Scripture mode, length, and CTA intelligently. Avoid recent content: ${JSON.stringify(recentItems)}. Attempt ${attempt + 1}. Return exactly five hashtags.`); result.hashtags = normalizeHashtags(result.hashtags); score = Math.max(...recentItems.map(item => similarity(result.title || result.headline || '', `${item.title || ''} ${item.hook || ''}`)), 0); if (score < 0.55) break; }
    const draftId = crypto.randomUUID(); const total = format === '3-Slide Carousel' ? 3 : format === '5-Slide Carousel' ? 5 : 1; const slides = total > 1 && Array.isArray(result.slides) && result.slides.length ? result.slides.slice(0, total) : Array.from({ length: total }, (_, index) => ({ slide: index + 1, headline: result.headline || result.title, body: result.supporting_text || result.hook })); const assetPaths: { slide: number; source: string; final: string }[] = [];
    for (const slide of slides) { const prompt = `Create a square cinematic editorial background for REBUKEEVIL. Style: ${visualStyle}. Category: ${category.name}. Subject: ${slide.headline}. Near-black, warm ivory, aged paper, iron, restrained muted red, analog grain. No text, no typography, no logo, no watermark, no fantasy glow, no gore.`; const source = await generateArtwork(prompt); const sourcePath = `${draftId}/source-${String(slide.slide).padStart(2, '0')}.webp`; const finalPath = `${draftId}/slide-${String(slide.slide).padStart(2, '0')}.svg`; const sourceUpload = await auth.client.storage.from('content-assets').upload(sourcePath, source, { contentType: 'image/webp', upsert: false }); if (sourceUpload.error) throw sourceUpload.error; uploaded.push(sourcePath); const finalUpload = await auth.client.storage.from('content-assets').upload(finalPath, Buffer.from(finalSlide(source, slide.headline, slide.body, slide.slide, total)), { contentType: 'image/svg+xml', upsert: false }); if (finalUpload.error) throw finalUpload.error; uploaded.push(finalPath); assetPaths.push({ slide: slide.slide, source: sourcePath, final: finalPath }); }
    const payload = { id: draftId, format, category: category.name, subcategory: category.subcategories[0], angle, audience: 'AUTOPILOT', title: result.title || result.headline, hook: result.hook, content: result, caption: result.caption, hashtags: result.hashtags, scripture: result.scripture, visual_direction: `${visualStyle} / ${template}. ${result.visual_direction || ''}`, image_prompts: slides.map((slide: any) => slide.visual_direction || visualStyle), asset_paths: assetPaths, status: 'DRAFT', created_by: auth.user.id }; const saved = await auth.client.from('content_drafts').insert(payload).select().single(); if (saved.error) throw saved.error;
    const urls = await Promise.all(assetPaths.map(async asset => ({ ...asset, url: (await auth.client.storage.from('content-assets').createSignedUrl(asset.final, 60 * 60)).data?.signedUrl || '' }))); const content = { ...saved.data.content, asset_urls: urls }; await auth.client.from('content_drafts').update({ content }).eq('id', draftId); await auth.client.from('content_generation_logs').insert({ generation_type: 'AUTOPILOT', model: process.env.OPENAI_MODEL || 'gpt-5.6-terra', input_summary: JSON.stringify({ format, category: category.name, angle, visualStyle, template }), output_id: draftId, created_by: auth.user.id }); return NextResponse.json({ draft: { ...saved.data, content, asset_urls: urls }, strategy: { format, category: category.name, angle, visualStyle, template, duplicateScore: Math.round(score * 100) } });
  } catch (error) { if (uploaded.length && auth.client) await auth.client.storage.from('content-assets').remove(uploaded); return NextResponse.json({ error: error instanceof Error ? error.message : 'Autopilot asset generation failed.' }, { status: 500 }); }
}
