'use client';
import { useEffect, useState } from 'react';
import { createClient } from '@/lib/supabase/client';
import type { CommunityPost, CommunityReport, Profile } from '@/lib/community-types';

export default function CommunityModeration() {
  const [reports, setReports] = useState<CommunityReport[]>([]); const [posts, setPosts] = useState<CommunityPost[]>([]); const [users, setUsers] = useState<Profile[]>([]); const [filter, setFilter] = useState('ALL'); const [message, setMessage] = useState(''); const client = createClient();
  async function load() { if (!client) return; const [reportResult, postResult, userResult] = await Promise.all([client.from('community_reports').select('*').order('created_at', { ascending: false }), client.from('community_posts').select('*').order('created_at', { ascending: false }), client.from('profiles').select('*').order('created_at', { ascending: false })]); setReports((reportResult.data || []) as CommunityReport[]); setPosts((postResult.data || []) as CommunityPost[]); setUsers((userResult.data || []) as Profile[]); }
  useEffect(() => { void load(); }, []);
  async function reportAction(report: CommunityReport, action: 'DISMISS' | 'REMOVE' | 'WARN') { if (!client) return; const auth = await client.auth.getUser(); if (action === 'REMOVE') { if (report.post_id) await client.from('community_posts').update({ is_deleted: true }).eq('id', report.post_id); if (report.reply_id) await client.from('community_replies').update({ is_deleted: true }).eq('id', report.reply_id); } if (action === 'WARN' && auth.data.user) { const target = report.post_id ? await client.from('community_posts').select('user_id').eq('id', report.post_id).maybeSingle() : await client.from('community_replies').select('user_id').eq('id', report.reply_id).maybeSingle(); if (target.data) await client.from('community_moderation_actions').insert({ moderator_user_id: auth.data.user.id, target_user_id: target.data.user_id, action: 'WARN' }); } await client.from('community_reports').update({ status: action === 'DISMISS' ? 'DISMISSED' : 'RESOLVED' }).eq('id', report.id); setMessage(action === 'DISMISS' ? 'REPORT DISMISSED' : action === 'WARN' ? 'USER WARNED' : 'CONTENT REMOVED'); await load(); }
  async function moderatePost(post: CommunityPost) { if (!client || !window.confirm(`${post.is_deleted ? 'Restore' : 'Remove'} "${post.title}"?`)) return; const auth = await client.auth.getUser(); const restoring = post.is_deleted; await client.from('community_posts').update({ is_deleted: !restoring }).eq('id', post.id); if (auth.data.user) await client.from('community_moderation_actions').insert({ moderator_user_id: auth.data.user.id, post_id: post.id, action: restoring ? 'RESTORE' : 'REMOVE' }); setMessage(restoring ? 'POST RESTORED' : 'POST REMOVED'); await load(); }
  async function banUser(user: Profile) { if (!client || !window.confirm(`${user.is_banned ? 'Unban' : 'Ban'} @${user.username}?`)) return; const auth = await client.auth.getUser(); await client.from('profiles').update({ is_banned: !user.is_banned }).eq('id', user.id); if (auth.data.user) await client.from('community_moderation_actions').insert({ moderator_user_id: auth.data.user.id, target_user_id: user.id, action: user.is_banned ? 'UNBAN' : 'BAN' }); setMessage(user.is_banned ? 'USER UNBANNED' : 'USER BANNED'); await load(); }
  const openReports = reports.filter(report => report.status === 'OPEN'); const shownPosts = filter === 'ALL' ? posts : posts.filter(post => post.type === filter); const postCount = (userId: string) => posts.filter(post => post.user_id === userId && !post.is_deleted).length; const reportCount = (userId: string) => reports.filter(report => report.reporter_user_id === userId).length;
  return <div className="mx-auto max-w-5xl"><header className="mb-14 border-b border-white/[.14] pb-8"><p className="mono text-[10px] text-[#85847d]">PRIVATE BETA / MODERATION</p><h1 className="display mt-4 text-[clamp(3rem,7vw,6rem)] leading-none">THE GARRISON</h1></header>{message && <p className="mb-6 mono text-[10px] text-[#a08b5c]">{message}</p>}<section><h2 className="display text-4xl">REPORTS <span className="mono text-sm text-[#85847d]">/ {openReports.length}</span></h2><div className="mt-5 space-y-2">{openReports.map(report => <div key={report.id} className="border border-[#343532] p-4"><p className="mono text-[10px] text-[#a08b5c]">{report.reason}</p><p className="mt-2 text-sm text-[#aaa9a1]">{report.details || 'No additional details.'}</p><div className="mt-4 flex flex-wrap gap-4"><button onClick={() => reportAction(report, 'DISMISS')} className="mono text-[9px]">DISMISS</button><button onClick={() => reportAction(report, 'WARN')} className="mono text-[9px]">WARN USER</button><button onClick={() => reportAction(report, 'REMOVE')} className="mono text-[9px] text-[#a87873]">REMOVE CONTENT</button></div></div>)}{!openReports.length && <p className="py-5 mono text-[10px] text-[#85847d]">NO OPEN REPORTS.</p>}</div></section><section className="mt-16"><div className="flex flex-wrap items-center justify-between gap-5"><h2 className="display text-4xl">POSTS <span className="mono text-sm text-[#85847d]">/ {posts.length}</span></h2><select value={filter} onChange={event => setFilter(event.target.value)} className="border border-[#343532] bg-[#050505] p-3 font-mono text-[10px] text-[#dedbd0]"><option>ALL</option><option>PRAYER</option><option>ACCOUNTABILITY</option><option>TESTIMONY</option></select></div><div className="mt-5 space-y-2">{shownPosts.map(post => <div key={post.id} className="flex items-center gap-5 border border-[#343532] p-4"><div className="min-w-0 flex-1"><p className="mono text-[9px] text-[#a08b5c]">{post.type}</p><p className="display mt-2 truncate text-2xl">{post.title}</p></div><button onClick={() => moderatePost(post)} className="mono text-[9px] text-[#a87873]">{post.is_deleted ? 'RESTORE' : 'REMOVE'}</button></div>)}</div></section><section className="mt-16"><h2 className="display text-4xl">USERS <span className="mono text-sm text-[#85847d]">/ {users.length}</span></h2><div className="mt-5 space-y-2">{users.map(user => <div key={user.id} className="flex items-center gap-5 border border-[#343532] p-4"><div className="flex-1"><p className="display text-2xl">@{user.username}</p><p className="mono mt-2 text-[9px] text-[#85847d]">JOINED {new Date(user.created_at).toLocaleDateString()} / POSTS {postCount(user.id)} / REPORTS {reportCount(user.id)} / {user.is_banned ? 'BANNED' : 'ACTIVE'}</p></div><button onClick={() => banUser(user)} className="mono text-[9px]">{user.is_banned ? 'UNBAN' : 'BAN'}</button></div>)}</div></section></div>;
}
